### ISSUE TITLE
emscripten_dispatch_to_thread_sync not found

### ISSUE THREAD

**Issue by aduda9** [luigifcruz/webusb-libusb#1]
Hi!

I'm trying to build this project, but it keeps failing because `emscripten_dispatch_to_thread_sync` isn't found. I think you mentioned creating something similar [here](https://github.com/emscripten-core/emscripten/issues/13287) - is `emscripten_dispatch_to_thread_sync` the same as `_emscripten_do_dispatch_to_thread2` in your emscripten fork?

Thanks, and very cool project btw!

**Comment by luigifcruz** [comment]
Hi! The `emscripten_dispatch_to_thread_sync` implementation is a little bit more complicated than that. You can check out all the changes in this [PR](https://github.com/emscripten-core/emscripten/pull/13315/files). Not sure why they didn't merge it yet.
